apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-pierre
  namespace: pierre-space-second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: devops.azurecr.io/nginx_pierre:${GIT_COMMIT}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: pierre-space-second
spec:
  selector:
      app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
