apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: pierre-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: devops.azurecr.io/pierre/nginx_pierre
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: pierre-space
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
      app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
