apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-pierre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pierre/test:159
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
      app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
